# FOR ONLY DEV, WITHOUT REVERSE PROXY (e.g nginx)
# API services have their own network so ssh really needed for only gateway/reverse proxy
version: '3.4'
    
services:
  api_gateway:
    hostname: "api_gateway"
    build:
      context: ./APIGateway
    restart: always
    volumes:
      - ${CERTIFICATE_PATH}:/https
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5003
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASS}
    ports:
      - ${GATEWAY_PORT}:80
      - ${GATEWAY_SSH_PORT}:443
    depends_on:
      - "test_api"
    networks:
      - docker_net

  test_api:
    hostname: "test_api"
    build: ./Microservices
    restart: always
    volumes:
      - ${CERTIFICATE_PATH}:/https
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASS}

    depends_on:
      - "rabbitmq"
    networks:
      - docker_net

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - docker_net
networks:
  docker_net:
    name: "services_net"